### ISSUE TITLE
Incorrect rendering at PDF

### ISSUE THREAD

**Issue by DmytroLitvinov** [conformist-mw/conformist-mw#1]
![Selection_1094](https://user-images.githubusercontent.com/16066485/143016175-da6efc31-fd04-4c79-b304-07faf8a01982.png)

**Comment by conformist-mw** [comment]
Fixed. Thanks

**Comment by DmytroLitvinov** [comment]
@conformist-mw , can you remind please the URL of a resume? And what have you used for building it?
